In [4]:
import torch

## torch中的tensor跟numpy中的ndarray差不多，但支持gpu加速

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [7]:
# 所有元素总数
x.numel()

12

In [13]:
X = x.reshape((3,4))
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
# 从均值为0，方差为1的正态分布中随机取值
torch.randn((3,4))

tensor([[-1.4199, -0.1581, -0.3237,  0.2522],
        [ 0.2975, -0.4978, -1.5096, -0.9919],
        [-1.2988,  0.5969,  0.2415, -0.0746]])

In [18]:
torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

## 运算符

In [19]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y

tensor([ 3.,  4.,  6., 10.])

In [20]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [22]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [23]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [24]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [25]:
# y = e ** x 求幂
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [27]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [28]:
# dim = 0 在行上操作， 1 在列上操作
torch.cat((X, Y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [29]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [30]:
X.sum()

tensor(66.)

### 广播机制

In [31]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
# 由于a和b分别是和矩阵，如果让它们相加，它们的形状不匹配。 
# 我们将两个矩阵广播为一个更大的矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

In [33]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [34]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [35]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
X[1,2] = 9

In [37]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [38]:
X[0:2, 0:2] = 0
X

tensor([[ 0.,  0.,  2.,  3.],
        [ 0.,  0.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

## 节省内存

In [39]:
Y
Z = torch.zeros_like(Y)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [41]:
print(id(Z))
Z[:] = X + Y
print(id(Z))

2696810805760
2696810805760


In [42]:
# X[:] = X + Y或X += Y  也是原地操作   但 X = X + Y不是
before = id(X)
X += Y
id(X) == before

True

In [46]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [47]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [48]:
X,Y

(tensor([[ 2.,  1.,  6.,  6.],
         [ 1.,  2., 12., 11.],
         [12., 12., 12., 12.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [49]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [50]:
X > Y

tensor([[False, False,  True,  True],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])

In [51]:
X >= Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])