In [2]:
import  os 

os.makedirs(os.path.join('..','data'),exist_ok = True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [4]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [6]:
# iloc (index location)
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# 以平均值填充 NAN (not a number)
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [7]:
inputs = pd.get_dummies(inputs, dummy_na=True)
# dummy_na 默认为False，是否把NA 值，作为一个离散值处理，默认不处理
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [8]:
import  torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [19]:
nan_num = data.isnull().sum(axis=0)
nan_max_id = nan_num.idxmax()
nan_num,nan_max_id

(NumRooms    2
 Alley       3
 Price       0
 dtype: int64,
 'Alley')

In [25]:
# 先指定某一行或某一列的标记， axis=0 在行上操作，axis=1 在列上操作
data.drop([nan_max_id], axis=1)

NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000

In [20]:
aa = torch.arange(4).reshape(2,2)
aa

tensor([[0, 1],
        [2, 3]])

In [21]:
aa.sum(axis = 1)

tensor([1, 5])

In [22]:
aa.sum(axis = 0)

tensor([2, 4])

In [9]:
a = torch.rand(3,3)
b = a.permute(1,0)
a,b

(tensor([[0.7855, 0.0271, 0.6354],
         [0.6905, 0.7168, 0.3352],
         [0.8195, 0.4681, 0.7679]]),
 tensor([[0.7855, 0.6905, 0.8195],
         [0.0271, 0.7168, 0.4681],
         [0.6354, 0.3352, 0.7679]]))

In [10]:
c = b.reshape(9)

In [11]:
c

tensor([0.7855, 0.6905, 0.8195, 0.0271, 0.7168, 0.4681, 0.6354, 0.3352, 0.7679])

In [12]:
c[0] = 100
c,b

(tensor([1.0000e+02, 6.9053e-01, 8.1951e-01, 2.7108e-02, 7.1681e-01, 4.6814e-01,
         6.3542e-01, 3.3517e-01, 7.6795e-01]),
 tensor([[0.7855, 0.6905, 0.8195],
         [0.0271, 0.7168, 0.4681],
         [0.6354, 0.3352, 0.7679]]))