In [1]:
import torch

In [2]:
x = torch.arange(4)

In [3]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
X = torch.arange(24).reshape(2,3,4)

In [9]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [10]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [11]:
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
a = 2
X = torch.arange(24).reshape(2,3,4)

In [13]:
a + X

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [14]:
(a * X).shape

torch.Size([2, 3, 4])

## 降维

In [15]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [16]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [17]:
A.sum(axis=0)

tensor([40., 45., 50., 55.])

In [18]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [19]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

## 非降维

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [23]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [25]:
# 沿某个轴计算A的累计总和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [26]:
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.],
        [ 8., 17., 27., 38.],
        [12., 25., 39., 54.],
        [16., 33., 51., 70.]])

## 向量点积

In [27]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, x.dot(y), torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [28]:
x * y

tensor([0., 1., 2., 3.])

In [29]:
torch.sum(x * y)

tensor(6.)

## 矩阵 * 向量

In [30]:
A, x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [31]:
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

## 矩阵 * 矩阵

In [34]:
B = torch.ones(4, 3)
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [35]:
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 范数

In [36]:
# L2 范数，模长
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [37]:
# L1 范数，绝对值之和
torch.abs(u).sum()

tensor(7.)

In [38]:
# 矩阵的Frobenius 范数是矩阵元素平方和的平方根
torch.norm(torch.ones(4, 9))

tensor(6.)

## test

In [39]:
X = torch.arange(24).reshape(2,3,4)

In [41]:
len(X)

2

In [42]:
X = torch.arange(16).reshape(2,2,2,2)
X

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])

In [43]:
len(X)

2

In [44]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [46]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [49]:
A / A.sum(axis=0)

tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])

In [57]:
# A / A.sum(axis=1) 出错
A / A.sum(axis=1, keepdims=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [52]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [54]:
X.sum(axis=0)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [55]:
X.sum(axis=1)

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [56]:
X.sum(axis=2)

tensor([[ 6, 22, 38],
        [54, 70, 86]])