In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)
x.grad

In [3]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
## y = 2 xT * x 关于 x 的梯度应为4 x

In [6]:
# 默认情况pytorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [7]:
# sum = x1 + x2 + x3 ... 所以计算出来的偏导全为1
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [8]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])