In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [5]:
def load_array(data_arrays, batch_size, is_train=True):   #@save
    """构造一个pytorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)
    
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [9]:
next(iter(data_iter))

[tensor([[ 0.9723, -0.3091],
         [-0.1199,  0.7741],
         [ 0.6548, -1.5341],
         [-1.0271,  1.2767],
         [ 1.7953, -1.0901],
         [ 1.0862,  0.2282],
         [ 0.0139,  1.1520],
         [-0.7457, -0.3975],
         [ 0.3050, -0.8248],
         [-0.4103, -0.9215]]),
 tensor([[ 7.2011],
         [ 1.3521],
         [10.7278],
         [-2.1800],
         [11.4962],
         [ 5.5877],
         [ 0.3223],
         [ 4.0498],
         [ 7.6225],
         [ 6.5168]])]

In [10]:
from torch import nn

In [12]:
# 输入样本的大小 2， 输出 1
# Sequential 将各个模型排列起来
net = nn.Sequential(nn.Linear(2, 1))

In [19]:
# 初始化模型参数
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [20]:
loss = nn.MSELoss()

In [23]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [25]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss{l:f}')

epoch 1, loss0.000350
epoch 2, loss0.000102
epoch 3, loss0.000102


In [26]:
w = net[0].weight.data
b = net[0].bias.data
w, b

(tensor([[ 1.9993, -3.4005]]), tensor([4.1998]))