In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()        

In [5]:
layer = CenteredLayer()
layer(torch.arange(5, dtype=torch.float32))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [8]:
Y = net(torch.rand(4, 8))
Y.mean()
# 平均值近似于 0

tensor(-5.1223e-09, grad_fn=<MeanBackward0>)

In [10]:
# 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [11]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.4394,  0.9218,  0.8721],
        [ 0.1716, -0.8461,  1.3286],
        [-0.2989, -0.1027,  1.4584],
        [ 0.7911,  0.4609, -2.3253],
        [ 2.0941, -0.3587, -1.0385]], requires_grad=True)

In [12]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.2100, 1.2463],
        [1.5492, 2.3311, 0.0000]])

In [15]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))

In [21]:
net(torch.rand(2, 64))

tensor([[5.4352],
        [7.0551]])